---
- name: Setup web server
  hosts: web1democom
  become: true

  tasks:
    - name: Install Apache2 package
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
    

    - name: change webserver content
      copy: 
        src: index.html
        dest: /var/www/html/index.html


